{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cchsflow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cchsflow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cchsflow/cchsflow_{{ version }}.tar.gz
  sha256: 4f48dc428f5b3e2336acecb7232d4ce9acdd581c15a534dfffd6a0cf590fceb2

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=0.8.2
    - r-haven >=1.1.2
    - r-magrittr
    - r-sjlabelled >=1.0.17
    - r-stringr >=1.2.0
  run:
    - r-base
    - r-dplyr >=0.8.2
    - r-haven >=1.1.2
    - r-magrittr
    - r-sjlabelled >=1.0.17
    - r-stringr >=1.2.0

test:
  commands:
    - $R -e "library('cchsflow')"           # [not win]
    - "\"%R%\" -e \"library('cchsflow')\""  # [win]

about:
  home: https://github.com/Big-Life-Lab/cchsflow
  license: MIT
  summary: "Supporting the use of the Canadian Community Health Survey (CCHS) by transforming
    variables from each cycle into harmonized, consistent versions that span survey
    cycles (currently, 2001 to 2018). CCHS data used in this library is accessed and
    adapted in accordance to the Statistics Canada Open Licence Agreement. This package
    uses rec_with_table(), which was developed from 'sjmisc' rec(). L\xFCdecke D (2018).
    \"sjmisc: Data and Variable Transformation Functions\". Journal of Open Source Software,
    3(26), 754. <doi:10.21105/joss.00754>."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec
